name: 'ngrinder'

services:
  controller:
    image: mint8846/ngrinder-controller:3.5.9-p1
    ports:
      - 80:80 
      - 16001:16001 
      - 12000-12009:12000-12009 
    volumes:
      - controller:/opt/ngrinder-controller 
    restart: always
  agent:
    image: mint8846/ngrinder-agent:3.5.9-p1
    volumes:
      - agent:/opt/ngrinder-agent 
    links:
      - controller 
    restart: always

  jenkins:
    image: jenkins/jenkins:lts
    platform: linux/amd64
    user: root
    ports:
      - "8081:8080"           
      - "50000:50000"         
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: always
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrinder-ngrok
    restart: always
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: http jenkins:8080
    
volumes:
  controller:
  agent:
  jenkins_home:
